### ISSUE TITLE
Excess runtime of 6s....reducing to 3s

### ISSUE THREAD

**Issue by SHRIYASH-BAND** [rahullgupta/codingninjas-data-structure-and-algorithms-cpp#4]
@rahullgupta @amanhex Suggestion on Split Array under /Tests.
Use logical OR ( | | ) instead of + operator.

Original Code Output
![image](https://user-images.githubusercontent.com/84434494/206898845-0483d9b0-a2f6-43e8-9c01-83fd18c50be0.png)

Suggested Output
![image](https://user-images.githubusercontent.com/84434494/206898456-587e7fdd-3b8a-40b8-b7a6-87ca062e7cb5.png)
```
#include <bits/stdc++.h>
using namespace std;

bool splitter(int  arr[] , int n , int start, int ls, int rs){


    if(start==n){
        return ls ==rs;
    }
    if(arr[start]%5==0)
        ls+=arr[start];
    else if(arr[start]%3==0)
        rs +=arr[start];
    else 
        return splitter(arr,n,start+1, ls +arr[start],rs) || splitter(arr ,n,start+1, ls,rs+ arr[start]);

    return splitter(arr,n,start+1,ls,rs);

}


bool splitArray(int *input, int size) {
    
   
   return splitter( input , size , 0 ,0 ,0);
}

```

**Comment by rahulkumarguptaa** [comment]
Thank you for your suggestion!!!! I will definitely update the code.
